const G={q:s=>document.querySelector(s),qa:s=>[...document.querySelectorAll(s)]};
const Games={
  ttt:null,c4:null,chess:null,checkers:null,ludo:null,uno:null,pong:null,snake:null
};
const COLORS={red:'#ef4444',green:'#10b981',yellow:'#facc15',blue:'#3b82f6'};
function rand(n){return Math.floor(Math.random()*n)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openGame(id){const ov=G.q('#gameOverlay'); ov.classList.add('open'); ov.dataset.game=id; G.q('#gameTitle').textContent=document.querySelector(`[data-game="${id}"]`)?.dataset.title||id; G.q('#gameSubtitle').textContent=document.querySelector(`[data-game="${id}"]`)?.dataset.subtitle||''; renderGame(id);}
function closeGame(){G.q('#gameOverlay').classList.remove('open'); if(G.q('#gameOverlay').dataset.game==='pong'&&Games.pong) Games.pong.stop(); if(G.q('#gameOverlay').dataset.game==='snake'&&Games.snake) Games.snake.stop(); G.q('#gameOverlay').dataset.game='';}
function setModeRow(modes,active,cb){return `<div class="game-mode-row">${modes.map(m=>`<button class="game-btn ${active===m?'active':''}" data-mode="${m}">${m==='friend'?'2 Players':m==='computer'?'Play with Computer':'Solo Game'}</button>`).join('')}</div>`}
function bindMode(cb){G.qa('[data-mode]').forEach(b=>b.onclick=()=>cb(b.dataset.mode))}
function renderGame(id){const body=G.q('#gameBody'); if(id==='ttt') return initTTT(body); if(id==='c4') return initC4(body); if(id==='chess') return initChess(body); if(id==='checkers') return initCheckers(body); if(id==='ludo') return initLudo(body); if(id==='uno') return initUNO(body); if(id==='pong') return initPong(body); if(id==='snake') return initSnake(body);}
function mount(html){G.q('#gameBody').innerHTML=html}
function initTTT(body){
  let mode='computer',b=Array(9).fill(''),turn='X',over=false; Games.ttt={};
  const paint=()=>{body.innerHTML=`${setModeRow(['friend','computer'],'computer'===mode?'computer':mode)}<div class="game-status" id="tttStatus"></div><div class="ttt-board">${b.map((v,i)=>`<button class="ttt-cell" data-i="${i}" ${v?'disabled':''}>${v}</button>`).join('')}</div><div class="game-toolbar"><button class="game-btn primary" id="tttReset">New game</button></div>`; bindMode(m=>{mode=m;reset();}); G.qa('.ttt-cell').forEach(x=>x.onclick=()=>move(+x.dataset.i)); G.q('#tttReset').onclick=reset; status();};
  const winner=()=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].find(([a,c,d])=>b[a]&&b[a]===b[c]&&b[a]===b[d]);
  const minimax=(board,p)=>{const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]; const w=lines.find(([a,c,d])=>board[a]&&board[a]===board[c]&&board[a]===board[d]); if(w)return board[w[0]]==='O'?10:-10;if(board.every(Boolean))return 0;let best=p==='O'?-Infinity:Infinity;for(let i=0;i<9;i++)if(!board[i]){board[i]=p;const s=minimax(board,p==='O'?'X':'O');board[i]='';best=p==='O'?Math.max(best,s):Math.min(best,s)}return best};
  function ai(){if(mode!=='computer'||turn!=='O'||over)return;let best=-Infinity,idx=-1;for(let i=0;i<9;i++)if(!b[i]){b[i]='O';let s=minimax(b,'X');b[i]='';if(s>best){best=s;idx=i}}if(idx>-1)move(idx,true)}
  function move(i,aiMove=false){if(over||b[i]||(mode==='computer'&&turn==='O'&&!aiMove))return;b[i]=turn;const w=winner();if(w||b.every(Boolean)){over=true;paint();if(w)w.forEach?null:null;return}turn=turn==='X'?'O':'X';paint();ai()}
  function status(){const st=G.q('#tttStatus');if(!st)return;const w=winner();st.textContent=w?`Player ${w[0]==='X'?'X':'O'} wins`:(over?'Draw':mode==='computer'?(turn==='X'?'Your turn':'Computer is thinking…'):`${turn}'s turn`);}
  function reset(){b=Array(9).fill('');turn='X';over=false;paint();status()}
  paint();
}
function initC4(body){
  let mode='computer',b=Array.from({length:6},()=>Array(7).fill(0)),turn=1,over=false;Games.c4={};
  const wins=()=>{for(let r=0;r<6;r++)for(let c=0;c<7;c++){const p=b[r][c];if(!p)continue;for(const [dr,dc] of [[1,0],[0,1],[1,1],[1,-1]]){let cells=[[r,c]];for(let k=1;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=6||cc<0||cc>=7||b[rr][cc]!==p)break;cells.push([rr,cc])}if(cells.length===4)return cells}}return null};
  function drop(c,p){for(let r=5;r>=0;r--)if(!b[r][c]){b[r][c]=p;return r}return -1}
  function ai(){if(mode!=='computer'||turn!==2||over)return;let choices=[3,2,4,1,5,0,6].filter(c=>b[0][c]===0);setTimeout(()=>{if(over)return;let c=choices[rand(choices.length)];let center=choices.find(x=>{const cp=b.map(row=>row.slice());for(let r=5;r>=0;r--)if(!cp[r][x]){cp[r][x]=2;break}return checkWinner(cp,2)}) ?? c;drop(center,2);if(checkWinner(b,2)||b.every(row=>row.every(Boolean)))over=true;else turn=1;paint();},280)}
  function checkWinner(board,p){for(let r=0;r<6;r++)for(let c=0;c<7;c++)for(const[dr,dc]of[[1,0],[0,1],[1,1],[1,-1]]){let ok=true;for(let k=0;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=6||cc<0||cc>=7||board[rr][cc]!==p){ok=false;break}}if(ok)return true}return false}
  function click(c){if(over||b[0][c]||(mode==='computer'&&turn===2))return;drop(c,turn);if(checkWinner(b,turn)||b.every(row=>row.every(Boolean)))over=true;else turn=turn===1?2:1;paint();ai()}
  function paint(){body.innerHTML=`${setModeRow(['friend','computer'],mode)}<div class="game-status">${over?(wins()?'Player '+turn+' wins':'Draw'):(mode==='computer'?(turn===1?'Your turn':'Computer is thinking…'):`Player ${turn}'s turn`)}</div><div class="c4-wrap"><div class="c4-board">${b.flatMap((row,r)=>row.map((v,c)=>`<button class="c4-cell ${v===1?'p1':v===2?'p2':''}" data-c="${c}" aria-label="Column ${c+1}"></button>`)).join('')}</div></div><div class="game-toolbar"><button class="game-btn primary" id="c4Reset">New game</button></div>`;bindMode(m=>{mode=m;reset()});G.qa('.c4-cell').forEach(x=>x.onclick=()=>click(+x.dataset.c));G.q('#c4Reset').onclick=reset}
  function reset(){b=Array.from({length:6},()=>Array(7).fill(0));turn=1;over=false;paint()}
  paint();
}
function initChess(body){
  let mode='computer'; let chessLib=window.Chess?new window.Chess():null; Games.chess={};
  const glyph={'p':'♟','r':'♜','n':'♞','b':'♝','q':'♛','k':'♚','P':'♙','R':'♖','N':'♘','B':'♗','Q':'♕','K':'♔'};
  const files=['a','b','c','d','e','f','g','h']; let selected=null,over=false;
  function pieceMap(){const m={}; if(!chessLib)return m; chessLib.board().forEach((row,r)=>row.forEach((p,c)=>{if(p)m[files[c]+(8-r)]=p.color==='w'?p.type.toUpperCase():p.type}));return m}
  function paint(){const m=pieceMap();body.innerHTML=`${setModeRow(['friend','computer'],mode)}<div class="game-status">${chessLib?chessLib.history().length===0?'White to move':(chessLib.isGameOver()?(chessLib.isCheckmate()?'Checkmate':'Game over'):(chessLib.turn()==='w'?'White to move':'Black to move')):'Chess library unavailable — refresh with internet enabled.'}</div><div class="chess-board">${Array.from({length:64},(_,i)=>{const r=Math.floor(i/8),c=i%8,sq=files[c]+(8-r),pc=m[sq],move=selected&&chessLib?chessLib.moves({square:selected,verbose:true}).some(x=>x.to===sq):false;return `<button class="chess-square ${(r+c)%2?'dark':'light'} ${selected===sq?'sel':''} ${move?'move':''}" data-sq="${sq}">${pc?`<span class="chess-piece">${glyph[pc]}</span>`:''}</button>`}).join('')}</div><div class="game-toolbar"><button class="game-btn primary" id="chessReset">New game</button></div>`;bindMode(m=>{mode=m;reset()});G.qa('.chess-square').forEach(x=>x.onclick=()=>click(x.dataset.sq));G.q('#chessReset').onclick=reset}
  function click(sq){if(!chessLib||over)return;const turn=chessLib.turn();if(mode==='computer'&&turn==='b')return;const p=chessLib.get(sq);if(selected){const moves=chessLib.moves({square:selected,verbose:true});if(moves.some(m=>m.to===sq)){chessLib.move({from:selected,to:sq,promotion:'q'});selected=null;over=chessLib.isGameOver();paint();if(mode==='computer'&&!over)setTimeout(ai,220);return}selected=null;}
    if(p&&p.color===turn)selected=sq;paint();}
  function ai(){if(!chessLib||over||chessLib.turn()!=='b')return;const moves=chessLib.moves({verbose:true});if(!moves.length)return;const m=moves[rand(moves.length)];chessLib.move(m);over=chessLib.isGameOver();paint()}
  function reset(){chessLib=window.Chess?new window.Chess():null;selected=null;over=false;paint()}
  paint();
}
function initCheckers(body){
  let mode='computer',turn='r',over=false;let b=Array.from({length:8},()=>Array(8).fill(null));Games.checkers={};
  for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r][c]={p:'b',k:false};for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r][c]={p:'r',k:false}; let sel=null;
  function movesFor(r,c){const piece=b[r][c];if(!piece)return[];const dirs=piece.k?[-1,1]:piece.p==='r'?[ -1 ]:[1];const out=[];for(const dr of dirs)for(const dc of[-1,1]){const rr=r+dr,cc=c+dc;if(rr>=0&&rr<8&&cc>=0&&cc<8&&!b[rr][cc])out.push({r:rr,c:cc,cap:null});else if(rr>=0&&rr<8&&cc>=0&&cc<8&&b[rr][cc]&&b[rr][cc].p!==piece.p){const r2=r+dr*2,c2=c+dc*2;if(r2>=0&&r2<8&&c2>=0&&c2<8&&!b[r2][c2])out.push({r:r2,c:c2,cap:{r:rr,c:cc}})}}return out}
  function allMoves(p){const arr=[];let captures=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]?.p===p){for(const m of movesFor(r,c)){const item={from:{r,c},...m};if(item.cap)captures.push(item);else arr.push(item)}}return captures.length?captures:arr}
  function doMove(m){const piece=b[m.from.r][m.from.c];b[m.from.r][m.from.c]=null;b[m.r][m.c]=piece;if(m.cap)b[m.cap.r][m.cap.c]=null;if((piece.p==='r'&&m.r===0)||(piece.p==='b'&&m.r===7))piece.k=true;turn=turn==='r'?'b':'r';if(!allMoves(turn).length)over=true;sel=null;paint();if(mode==='computer'&&turn==='b'&&!over)setTimeout(ai,240)}
  function ai(){const ms=allMoves('b');if(!ms.length)return;doMove(ms[rand(ms.length)])}
  function click(r,c){if(over||(mode==='computer'&&turn==='b'))return;const p=b[r][c];if(sel){const ms=movesFor(sel.r,sel.c);const m=ms.find(x=>x.r===r&&x.c===c);if(m){doMove({from:sel,...m});return}sel=null}if(p?.p===turn)sel={r,c};paint()}
  function paint(){body.innerHTML=`${setModeRow(['friend','computer'],mode)}<div class="game-status">${over?'Game over':`${turn==='r'?'Red':'Black'} turn`}</div><div class="checkers-board">${Array.from({length:64},(_,i)=>{const r=Math.floor(i/8),c=i%8,p=b[r][c],selected=sel?.r===r&&sel?.c===c;return `<div class="checker-cell ${(r+c)%2?'dark':'light'}" data-r="${r}" data-c="${c}">${p?`<div class="checker-piece ${p.p==='r'?'red':'black'} ${p.k?'king':''}" title="${p.k?'King':''}"></div>`:''}</div>`}).join('')}</div><div class="game-toolbar"><button class="game-btn primary" id="checkReset">New game</button></div>`;bindMode(m=>{mode=m;reset()});G.qa('.checker-cell').forEach(x=>x.onclick=()=>click(+x.dataset.r,+x.dataset.c));G.q('#checkReset').onclick=reset}
  function reset(){b=Array.from({length:8},()=>Array(8).fill(null));for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r][c]={p:'b',k:false};for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2)b[r][c]={p:'r',k:false};turn='r';over=false;sel=null;paint()}
  paint();
}
function initLudo(body){
  let mode='friend',players=mode==='friend'?2:2,turn=0,dice=0,over=false;let tokens=[];Games.ludo={};
  function reset(){players=2;turn=0;dice=0;over=false;tokens=Array.from({length:players},()=>Array(4).fill(-1));paint()}
  function roll(){if(over)return;dice=1+rand(6);if(dice!==6&&!tokens[turn].some(x=>x>=0&&x<57)){next();paint();return}if(mode==='computer'&&turn===1){setTimeout(ai,260)}else paint()}
  function moveToken(i){if(over||dice===0)return;let pos=tokens[turn][i];if(pos===-1&&dice===6)pos=0;else if(pos>=0&&pos+dice<=57)pos+=dice;else return;tokens[turn][i]=pos;if(pos===57&&tokens[turn].every(x=>x===57))over=true; if(!over&&dice!==6)next();dice=0;paint();if(mode==='computer'&&turn===1&&!over)setTimeout(ai,260)}
  function next(){turn=(turn+1)%players;}
  function ai(){let options=tokens[1].map((p,i)=>({p,i})).filter(x=>(x.p===-1&&dice===6)||(x.p>=0&&x.p+dice<=57));if(options.length)moveToken(options[rand(options.length)].i);else{dice=0;next();paint()}}
  function paint(){body.innerHTML=`${setModeRow(['friend','computer'],mode)}<div class="game-status">${over?`${turn===0?'Player 1':'Player 2'} wins!`:mode==='computer'?(turn===0?'Your turn':'Computer turn'):`Player ${turn+1}'s turn`}</div><div class="dice-box"><div class="dice">${dice||'–'}</div><button class="game-btn primary" id="ludoRoll">Roll dice</button></div><div class="ludo-board">${Array.from({length:225},(_,i)=>{const r=Math.floor(i/15),c=i%15;let cls='ludo-cell';if((r<6&&c<6))cls+=' ludo-home-red';else if((r<6&&c>8))cls+=' ludo-home-green';else if((r>8&&c<6))cls+=' ludo-home-yellow';else if((r>8&&c>8))cls+=' ludo-home-blue';else cls+=' ludo-path';let token='';const idx=tokens.findIndex((arr,p)=>{const pos=(r*15+c)%58;return arr.some(x=>x===pos)});if(idx>=0){const ti=tokens[idx].findIndex(x=>x===((r*15+c)%58));token=`<span class="ludo-token ${['red','green','yellow','blue'][idx]}"></span>`;}
return `<div class="${cls}">${token}</div>`}).join('')}</div><div class="game-toolbar">${tokens[turn].map((x,i)=>`<button class="game-btn" data-token="${i}">Token ${i+1} · ${x<0?'Home':x+'/57'}</button>`).join('')}</div><div class="game-footnote">Ludo race board: roll 6 to leave home, reach 57 to finish.</div>`;bindMode(m=>{mode=m;reset()});G.q('#ludoRoll').onclick=roll;G.qa('[data-token]').forEach(x=>x.onclick=()=>moveToken(+x.dataset.token))}
  reset();
}
function buildUnoDeck(){const colors=['red','green','blue','yellow'];const d=[];for(const c of colors){d.push({c,n:0});for(let n=1;n<=9;n++){d.push({c,n},{c,n})}}for(let i=0;i<8;i++)d.push({c:'wild',n:'+'});for(let i=0;i<4;i++)d.push({c:'wild',n:'W'});return d.sort(()=>Math.random()-.5)}
function initUNO(body){
  let mode='computer',deck=[],p1=[],p2=[],discard=null,turn='p1',over=false;Games.uno={};
  function reset(){deck=buildUnoDeck();p1=deck.splice(0,7);p2=deck.splice(0,7);discard=deck.find(c=>c.c!=='wild')||deck.pop();deck=deck.filter(x=>x!==discard);turn='p1';over=false;paint()}
  const playable=c=>c?.c==='wild'||c?.c===discard?.c||c?.n===discard?.n;
  function draw(hand){if(!deck.length){deck=buildUnoDeck();}hand.push(deck.pop())}
  function activeHand(){return turn==='p1'?p1:p2}
  function afterPlay(){const h=activeHand();if(!h.length){over=true;paint();return}turn=turn==='p1'?'p2':'p1';paint();if(mode==='computer'&&turn==='p2')setTimeout(cpuTurn,320)}
  function play(i){if(over)return;const h=activeHand(),c=h[i];if(!playable(c))return;discard=c;h.splice(i,1);afterPlay()}
  function cpuTurn(){if(over||mode!=='computer'||turn!=='p2')return;const idx=p2.findIndex(playable);if(idx>=0){discard=p2.splice(idx,1)[0]}else draw(p2);if(!p2.length){over=true;paint();return}turn='p1';paint()}
  function paint(){const h=activeHand();const activeName=mode==='computer'?(turn==='p1'?'You':'Computer'):(turn==='p1'?'Player 1':'Player 2');body.innerHTML=`${setModeRow(['friend','computer'],mode)}<div class="game-status">${over?(p1.length===0?'Player 1 wins!':(p2.length===0?'Player 2 wins!':'Game over')):`${activeName}'s turn`}</div><div class="uno-layout"><section class="uno-hand"><strong>${mode==='computer'?'Computer':'Player 2'} · ${p2.length} cards</strong><div class="game-footnote">${mode==='computer'?'Cards are hidden':'Pass the device after each turn'}</div></section><section class="uno-center"><div class="game-score"><div class="score-pill"><strong>${discard?.n??''}</strong><span>Current card</span></div><div class="score-pill"><strong>${h.length}</strong><span>${mode==='computer'?'Your cards':turn==='p1'?'Player 1 cards':'Player 2 cards'}</span></div></div><div class="uno-cards">${h.map((c,i)=>`<button class="uno-card uno-${c.c}" data-i="${i}"><span>${c.n==='+'?'↥':c.n==='W'?'★':c.n}</span><small>${c.c}</small></button>`).join('')}</div><div class="uno-legend">Playable: same color, same number/action, or wild.</div></section></div><div class="game-toolbar"><button class="game-btn" id="unoDraw" ${over?'disabled':''}>Draw card</button><button class="game-btn primary" id="unoReset">New game</button></div>`;bindMode(m=>{mode=m;reset()});G.qa('.uno-card').forEach(x=>x.onclick=()=>play(+x.dataset.i));G.q('#unoDraw').onclick=()=>{if(over)return;draw(activeHand());turn=turn==='p1'?'p2':'p1';paint();if(mode==='computer'&&turn==='p2')setTimeout(cpuTurn,320)};G.q('#unoReset').onclick=reset}
  reset();
}
function initPong(body){
  let mode='computer';let raf=0;Games.pong={stop:()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',Games.pong._kd);window.removeEventListener('keyup',Games.pong._ku)}};
  function start(){Games.pong.stop();const c=document.querySelector('#pongCanvas'),ctx=c.getContext('2d');c.width=960;c.height=540;const s={py:220,cy:220,by:270,bx:480,bvx:5,bvy:3,score:[0,0]};let up=false,down=false,p2up=false,p2down=false;const kd=e=>{if(e.key==='ArrowUp')up=true;if(e.key==='ArrowDown')down=true;if(e.key==='w'||e.key==='W')p2up=true;if(e.key==='s'||e.key==='S')p2down=true};const ku=e=>{if(e.key==='ArrowUp')up=false;if(e.key==='ArrowDown')down=false;if(e.key==='w'||e.key==='W')p2up=false;if(e.key==='s'||e.key==='S')p2down=false};Games.pong._kd=kd;Games.pong._ku=ku;window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);const resetBall=d=>{s.bx=480;s.by=270;s.bvx=5*d;s.bvy=Math.random()*4-2};const loop=()=>{if(!G.q('#pongCanvas'))return;if(up)s.py-=7;if(down)s.py+=7;s.py=Math.max(0,Math.min(460,s.py));if(mode==='computer')s.cy+=(s.by-(s.cy+40))*.085;else{if(p2up)s.cy-=7;if(p2down)s.cy+=7}s.cy=Math.max(0,Math.min(460,s.cy));s.bx+=s.bvx;s.by+=s.bvy;if(s.by<10||s.by>530)s.bvy*=-1;if(s.bx<100&&s.by>s.py&&s.by<s.py+80&&s.bvx<0){s.bvx=Math.abs(s.bvx)+.2;s.bvy+=(s.by-(s.py+40))*.05}if(s.bx>860&&s.by>s.cy&&s.by<s.cy+80&&s.bvx>0){s.bvx=-Math.abs(s.bvx)-.2}s.bx<0&&(s.score[1]++,resetBall(1));s.bx>960&&(s.score[0]++,resetBall(-1));ctx.clearRect(0,0,960,540);ctx.fillStyle='#111827';ctx.fillRect(0,0,960,540);ctx.fillStyle='#fff';ctx.fillRect(40,s.py,18,80);ctx.fillRect(902,s.cy,18,80);ctx.beginPath();ctx.arc(s.bx,s.by,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,255,255,.22)';ctx.fillRect(478,0,4,540);ctx.font='700 46px Inter';ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText(s.score[0],430,62);ctx.fillText(s.score[1],530,62);raf=requestAnimationFrame(loop)};loop()}
  body.innerHTML=`${setModeRow(['friend','computer'],mode)}<div class="game-status">Player 1: Arrow ↑/↓ · Player 2: W/S. In computer mode the right paddle is AI.</div><div class="canvas-wrap"><canvas id="pongCanvas" class="game-canvas"></canvas></div><div class="game-toolbar"><button class="game-btn primary" id="pongRestart">Restart</button></div>`;bindMode(m=>{mode=m;start()});G.q('#pongRestart').onclick=start;start();
}
function initSnake(body){Games.snake?.stop?.();let running=true,raf=0,dir={x:1,y:0},next={x:1,y:0},snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}],food={x:15,y:10},score=0;const size=24,c=document.createElement('canvas');c.width=c.height=480;c.className='snake-canvas';Games.snake={stop:()=>{running=false;cancelAnimationFrame(raf);window.removeEventListener('keydown',onKey)}};body.innerHTML=`<div class="game-status">Solo game · Use Arrow keys or WASD</div><div class="canvas-wrap" id="snakeWrap"></div><div class="game-score"><div class="score-pill"><strong id="snakeScore">0</strong><span>Score</span></div></div><div class="game-toolbar"><button class="game-btn primary" id="snakeRestart">Restart</button></div>`;G.q('#snakeWrap').appendChild(c);const ctx=c.getContext('2d');function rndFood(){do{food={x:rand(20),y:rand(20)}}while(snake.some(p=>p.x===food.x&&p.y===food.y))}function draw(dead){ctx.fillStyle='#0b1220';ctx.fillRect(0,0,480,480);ctx.fillStyle='#22304a';for(let x=0;x<20;x++)for(let y=0;y<20;y++)ctx.fillRect(x*24,y*24,1,1);ctx.fillStyle='#f43f5e';ctx.fillRect(food.x*24+4,food.y*24+4,16,16);snake.forEach((p,i)=>{ctx.fillStyle=i===0?'#7c8cff':'#3b82f6';ctx.fillRect(p.x*24+2,p.y*24+2,20,20)});if(dead){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(0,0,480,480);ctx.fillStyle='#fff';ctx.font='700 26px Inter';ctx.textAlign='center';ctx.fillText('Game Over',240,220);ctx.font='500 15px Inter';ctx.fillText('Press Restart to play again',240,248)}}function onKey(e){const k=e.key.toLowerCase();const map={arrowup:{x:0,y:-1},w:{x:0,y:-1},arrowdown:{x:0,y:1},s:{x:0,y:1},arrowleft:{x:-1,y:0},a:{x:-1,y:0},arrowright:{x:1,y:0},d:{x:1,y:0}};const nd=map[k];if(nd&&!(nd.x===-dir.x&&nd.y===-dir.y))next=nd}window.addEventListener('keydown',onKey);function loop(){if(!running)return;dir=next;const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(h.x<0||h.x>=20||h.y<0||h.y>=20||snake.some(p=>p.x===h.x&&p.y===h.y)){running=false;draw(true);return}snake.unshift(h);if(h.x===food.x&&h.y===food.y){score++;G.q('#snakeScore').textContent=score;rndFood()}else snake.pop();draw(false);raf=setTimeout(()=>requestAnimationFrame(loop),90)}loop()}
function initTheme(){document.documentElement.dataset.theme=localStorage.getItem('cunnact_theme')==='dark'?'dark':'light';G.q('#gameThemeBtn').onclick=()=>{const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.setItem('cunnact_theme',d?'light':'dark')}}
function boot(){initTheme();G.qa('[data-game]').forEach(c=>c.querySelector('.game-play-btn').onclick=()=>openGame(c.dataset.game));G.q('#gameClose').onclick=closeGame;G.q('#gameOverlay').addEventListener('click',e=>{if(e.target.id==='gameOverlay')closeGame()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeGame()})}
window.addEventListener('DOMContentLoaded',boot);
